-- AlterTable
ALTER TABLE "User" ADD COLUMN     "hrZone1Max" INTEGER NOT NULL DEFAULT 114,
ADD COLUMN     "hrZone2Max" INTEGER NOT NULL DEFAULT 133,
ADD COLUMN     "hrZone3Max" INTEGER NOT NULL DEFAULT 152,
ADD COLUMN     "hrZone4Max" INTEGER NOT NULL DEFAULT 171;

-- AlterTable
ALTER TABLE "Workout" ADD COLUMN     "hrZone1Min" DOUBLE PRECISION,
ADD COLUMN     "hrZone2Min" DOUBLE PRECISION,
ADD COLUMN     "hrZone3Min" DOUBLE PRECISION,
ADD COLUMN     "hrZone4Min" DOUBLE PRECISION,
ADD COLUMN     "hrZone5Min" DOUBLE PRECISION;
